// Portfolio project data structure
export interface PortfolioProject {
    id: string;
    title: string;
    slug: string;
    category: string;
    client: string;
    year: string;
    description: string;
    image: string;
    tags: string[];
    services: string[];
}

// Sample portfolio projects
export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
    {
        id: '1',
        title: 'Logo Design',
        slug: 'logo-design',
        category: 'Logo Design',
        client: 'Various Clients',
        year: '2025',
        description: 'Diverse logo portfolio featuring DoubleU Tech Biz, Neo Grace Medical Centre, ThinkIT, AlterFibre, Sure Cleaning, NeXtra, Zenith Solutions, and more.',
        image: '/assets/portfolio/logos.png',
        tags: ['Identity', 'Vector', 'Minimalist'],
        services: ['Brand Management'],
    },
    {
        id: '2',
        title: 'Brand Design',
        slug: 'brand-design',
        category: 'Brand Design',
        client: 'TechVenture Inc.',
        year: '2025',
        description: 'Comprehensive brand identity systems including guidelines and visual assets.',
        image: '/assets/cases/case-1.png',
        tags: ['Identity System', 'Guidelines', 'Visual Language'],
        services: ['Brand Management'],
    },
    {
        id: '9',
        title: 'Custom Branded Hoodies',
        slug: 'branded-hoodies',
        category: 'Brand Design',
        client: 'Energy Fitness',
        year: '2025',
        description: 'High-quality custom designed hoodies and apparel styling.',
        image: '/assets/portfolio/branded-hoodies.png',
        tags: ['Merchandise', 'Apparel', 'Branding'],
        services: ['Branding & Merchandise'],
    },
    {
        id: '10',
        title: 'Corporate Calendars',
        slug: 'desktop-calendars',
        category: 'Brand Design',
        client: 'Sauti Justice',
        year: '2026',
        description: 'Custom desktop calendars and branded stationery materials.',
        image: '/assets/portfolio/calendars.png',
        tags: ['Stationery', 'Print', 'Corporate Gift'],
        services: ['Branding & Merchandise'],
    },
    {
        id: '11',
        title: 'Humanitarian Brand Materials',
        slug: 'kaalmo-branding',
        category: 'Brand Design',
        client: 'Kaalmo Relief',
        year: '2024',
        description: 'Branded notebooks and field materials for relief and development agencies.',
        image: '/assets/portfolio/kaalmo.png',
        tags: ['Stationery', 'NGO', 'Print'],
        services: ['Brand Management'],
    },
    {
        id: '12',
        title: 'Office Branding',
        slug: 'office-branding',
        category: 'Brand Design',
        client: 'Bilkheir Travel',
        year: '2025',
        description: 'Interior branding and signage solutions for corporate offices.',
        image: '/assets/portfolio/office-branding.png',
        tags: ['Signage', 'Interior', 'Physical Branding'],
        services: ['Brand Management'],
    },
    {
        id: '14',
        title: 'Premium Letterheads',
        slug: 'letterheads',
        category: 'Brand Design',
        client: 'Various Clients',
        year: '2025',
        description: 'Corporate letterhead designs for Acacia, ThinkIT, ActiveBoard Consulting, and more.',
        image: '/assets/portfolio/letterheads.png',
        tags: ['Stationery', 'Corporate Identity', 'Print'],
        services: ['Brand Management'],
    },
    {
        id: '15',
        title: 'Event Branding',
        slug: 'event-branding',
        category: 'Brand Design',
        client: 'Various Clients',
        year: '2025',
        description: 'Complete event branding solutions including backdrops, flags, and merchandise for trade shows and summits.',
        image: '/assets/portfolio/event-branding.png',
        tags: ['Events', 'Large Format Print', 'Merchandise'],
        services: ['Branding & Merchandise'],
    },
    {
        id: '3',
        title: 'Web Design',
        slug: 'web-design',
        category: 'Web Design',
        client: 'Future Tech',
        year: '2025',
        description: 'Modern, responsive website designs aimed at user engagement and conversion.',
        image: '/assets/portfolio/startup-1.png',
        tags: ['UI/UX', 'Responsive', 'Web Development'],
        services: ['Startup Solutions'],
    },
    {
        id: '4',
        title: 'Brochures',
        slug: 'brochures',
        category: 'Brochures',
        client: 'Various Clients',
        year: '2024',
        description: 'Professional brochure layouts for Fineview Park, Lifeline Humanity Aid, Collonaire Security Group, and Winfas Contractors.',
        image: '/assets/portfolio/brochures.png',
        tags: ['Layout', 'Print', 'Marketing Material'],
        services: ['Corporate Documents'],
    },
    {
        id: '5',
        title: 'Profiles',
        slug: 'profiles',
        category: 'Profiles',
        client: 'Various Clients',
        year: '2024',
        description: 'Company profiles for Mosschem Paints, Madeline Kamau & Co. Advocates, Tayba Farms, and Greenpath Logistics.',
        image: '/assets/portfolio/profiles.png',
        tags: ['Company Profile', 'Editorial', 'Layout'],
        services: ['Corporate Documents'],
    },
    {
        id: '6',
        title: 'Reports',
        slug: 'reports',
        category: 'Reports',
        client: 'Various Clients',
        year: '2025',
        description: 'Executive reports including Coast Food and Nutrition Security, Drought Emergency Response Appeal, and Advocacy & Messaging Briefs.',
        image: '/assets/portfolio/reports.png',
        tags: ['Annual Report', 'Data Viz', 'Typography'],
        services: ['Corporate Documents'],
    },
    {
        id: '7',
        title: 'Digital Marketing',
        slug: 'digital-marketing',
        category: 'Digital Marketing',
        client: 'Growth Co.',
        year: '2025',
        description: 'Strategic digital marketing assets for social media and online campaigns.',
        image: '/assets/portfolio/social-1.png',
        tags: ['Social Media', 'Ads', 'Content Strategy'],
        services: ['Social Media Management'],
    },
    {
        id: '13',
        title: 'Social Media Campaigns',
        slug: 'social-media-campaigns',
        category: 'Digital Marketing',
        client: 'Various Clients',
        year: '2025',
        description: 'Creative social media content for Mountain View Technical, Amani Homes, Lyn Bakers, and more.',
        image: '/assets/portfolio/social-media-ads.png',
        tags: ['Social Media', 'Real Estate', 'Hospitality'],
        services: ['Digital Marketing'],
    },
    {
        id: '8',
        title: 'Business Cards',
        slug: 'business-cards',
        category: 'Business Cards',
        client: 'Various Clients',
        year: '2024',
        description: 'Premium business card designs for Sylvester Ouma Ochola, Atlantic FuelEx, SHL, UrbanCrest, Kevin Mathenge, and others.',
        image: '/assets/portfolio/business-cards.png',
        tags: ['Stationery', 'Print', 'Networking'],
        services: ['Branding & Merchandise'],
    },
];

export const PORTFOLIO_CATEGORIES = [
    'All',
    'Logo Design',
    'Brand Design',
    'Web Design',
    'Brochures',
    'Profiles',
    'Reports',
    'Digital Marketing',
    'Business Cards',
];
